#Experiment 1: TensorFlow Installation & Version Check

In [1]:
pip install tensorflow

#Experiment 2: Creating and Printing Tensors

In [2]:
import tensorflow as tf
print("TensorFlow Version:", tf.__version__)


TensorFlow Version: 2.19.0


In [11]:
scalar = tf.constant(10)
print("Scalar : ",scalar)

vector = tf.constant([1, 2, 3, 4])
print("Vector : " ,vector)

matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix : ",matrix)

t3=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Three Dimensional Scalar :", t3)

Scalar :  tf.Tensor(10, shape=(), dtype=int32)
Vector :  tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Matrix :  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Three Dimensional Scalar : tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


#Experiment 3: Basic Tensor Operations

In [12]:
a = tf.constant(5)
b = tf.constant(2)

print("=== Scalar Operations ===")
print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))
print("Power (a^b):", tf.pow(a, b))



=== Scalar Operations ===
Addition: tf.Tensor(7, shape=(), dtype=int32)
Subtraction: tf.Tensor(3, shape=(), dtype=int32)
Multiplication: tf.Tensor(10, shape=(), dtype=int32)
Division: tf.Tensor(2.5, shape=(), dtype=float64)
Power (a^b): tf.Tensor(25, shape=(), dtype=int32)



In [13]:
a = tf.constant([5, 10, 15])
b = tf.constant([1, 2, 3])

print("=== Vector Operations ===")
print("Addition:", tf.add(a, b))
print("Subtraction:", tf.subtract(a, b))
print("Multiplication:", tf.multiply(a, b))
print("Division:", tf.divide(a, b))
print("Power (a^b):", tf.pow(a, b))


=== Vector Operations ===
Addition: tf.Tensor([ 6 12 18], shape=(3,), dtype=int32)
Subtraction: tf.Tensor([ 4  8 12], shape=(3,), dtype=int32)
Multiplication: tf.Tensor([ 5 20 45], shape=(3,), dtype=int32)
Division: tf.Tensor([5. 5. 5.], shape=(3,), dtype=float64)
Power (a^b): tf.Tensor([   5  100 3375], shape=(3,), dtype=int32)



In [14]:
a = tf.constant([[2, 4],
                 [6, 8]])

b = tf.constant([[1, 2],
                 [3, 4]])

print("=== Matrix Operations ===")
print("Addition:\n", tf.add(a, b))
print("Subtraction:\n", tf.subtract(a, b))
print("Multiplication (element-wise):\n", tf.multiply(a, b))
print("Division:\n", tf.divide(a, b))
print("Power (a^b):\n", tf.pow(a, b))

=== Matrix Operations ===
Addition:
 tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)
Subtraction:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Multiplication (element-wise):
 tf.Tensor(
[[ 2  8]
 [18 32]], shape=(2, 2), dtype=int32)
Division:
 tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float64)
Power (a^b):
 tf.Tensor(
[[   2   16]
 [ 216 4096]], shape=(2, 2), dtype=int32)


#Experiment 4: Data Types and Shape of Tensors

In [15]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

print("Tensor:", a)
print("Data Type:", a.dtype)
print("Shape:", a.shape)
print("Number of Dimensions:", a.ndim)

Tensor: tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Data Type: <dtype: 'int32'>
Shape: (2, 3)
Number of Dimensions: 2


#Experiment 5: Converting NumPy Arrays to Tensors

In [16]:
import numpy as np
import tensorflow as tf

# NumPy array
a = np.array([10, 20, 30, 40])

# Convert to Tensor
b = tf.convert_to_tensor(a)

print("NumPy Array:", a)
print("TensorFlow Tensor:", b)


NumPy Array: [10 20 30 40]
TensorFlow Tensor: tf.Tensor([10 20 30 40], shape=(4,), dtype=int64)
